Bump to react-jsx 3
This change fixes a compilation error with bsb 8.3.1:

  Error: Unsupported jsx version 2
  For more details, please checkout the schema
  https://rescript-lang.org/docs/manual/latest/build-configuration#reason-refmt-old